name: Deploy Docs to GitHub Page

on:
  push:
    branches:
      - master
    paths:
      - 'site/docs/**'
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Root And Docs
        run: |
          npm install -g pnpm
          pnpm update
      - name: Build
        run: |
          npm run build:jayden-ui
          npm run build:docs

      - name: Move Build Files
        run: |
          mkdir gh-page
          mv ./site/docs/.vitepress/dist/* ./gh-page/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          CLEAN: true
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-page
          FOLDER: ./gh-page
