name: Deploy to Git Pages

on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Git Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: true # 清空部署目录
          branch: gh-page # 部署分支
          folder: ../../site/docs/.vitepress/dist # 部署目录